import './endpoints/auth'
import './endpoints/products'
import './endpoints/search'
import './endpoints/orders'
import './endpoints/suppliers'
import './endpoints/restaurants'
import './endpoints/prices'
import './endpoints/inventory'
import './endpoints/warehouses'
import './endpoints/dashboard'
import './endpoints/files'
import './endpoints/chat'
import './endpoints/restaurantInventory'
import './endpoints/receiving'
import './endpoints/quickLists'
import './endpoints/finance'
import './endpoints/branches'
import './endpoints/notifications'
import './endpoints/public'
import './endpoints/staffPortal'
import './endpoints/reports'
import './endpoints/disputes'
import './endpoints/creditNotes'
import './endpoints/promotions'
import './endpoints/contractPricing'
import './endpoints/reviews'
import './endpoints/tenantAudit'
import './endpoints/amendments'
import './endpoints/push'
import './endpoints/billing'
import './endpoints/admin'
import './endpoints/impersonation'
import '../staffApi'
import '../reservationsApi'
import '../consumerApi'

import { api as baseApi } from './base'

// Endpoint modules inject into `api` at import time; loosen typing for imperative access.
export const api = baseApi as any

export const {
  useGetMeQuery,
  useGetAdminPreferencesQuery,
  useUpdateAdminPreferencesMutation,
  useGetInviteSessionQuery,
  useGetRegisterStatusQuery,
  useCompleteRegistrationMutation,
  useSubmitLegalReacceptanceMutation,
  useLogoutMutation,
  useGetProductsQuery,
  useGetProductCategoriesQuery,
  useGetProductTagsQuery,
  useGetProductQuery,
  useCreateProductMutation,
  useUpdateProductMutation,
  useGetProductFavoritesQuery,
  useFavoriteProductMutation,
  useUnfavoriteProductMutation,
  useSearchQuery,
  useGetSearchHistoryQuery,
  useUpsertSearchHistoryMutation,
  useDeleteSearchHistoryMutation,
  useGetOrdersQuery,
  useGetOrderQuery,
  useCreateOrderMutation,
  useCreateManualOrderMutation,
  useUpdateOrderMutation,
  useSendOrderReminderMutation,
  useGetFulfillmentBoardQuery,
  useGetFulfillmentRoutesQuery,
  useGetFulfillmentRouteQuery,
  useGetDriverActiveRouteQuery,
  useBuildDriverRouteFromAssignmentsMutation,
  useCreateFulfillmentRouteMutation,
  useUpdateFulfillmentRouteMutation,
  useCancelFulfillmentRouteMutation,
  useReorderFulfillmentRouteStopsMutation,
  useSetNextFulfillmentRouteStopMutation,
  useUpdateFulfillmentRouteStopMutation,
  useGetFulfillmentExceptionsQuery,
  useGetFulfillmentDispatchQuery,
  useGetDriversQuery,
  useGetUnlinkedDriversQuery,
  useCreateDriverMutation,
  useUpdateDriverMutation,
  useDeactivateDriverMutation,
  useAssignDriverToOrderMutation,
  useReassignDriverOnOrderMutation,
  useUpdateOrderDeliveryStatusMutation,
  useRolloverAssignmentToTomorrowMutation,
  useSendDriverLocationMutation,
  useGetOrderTrackingQuery,
  useSubmitOrderProofOfDeliveryMutation,
  useResolveFulfillmentExceptionMutation,
  useIgnoreFulfillmentExceptionMutation,
  useGetSuppliersQuery,
  useGetSupplierQuery,
  useGetSupplierStatisticsQuery,
  useFollowSupplierMutation,
  useUnfollowSupplierMutation,
  useGetSupplierMeQuery,
  useUpdateSupplierMutation,
  useUploadSupplierLogoMutation,
  useGetRestaurantMeQuery,
  useGetTenantBrandingQuery,
  useUpdateTenantBrandingMutation,
  useUpdateRestaurantMutation,
  useGetRestaurantDeliveryLocationsQuery,
  useUpdateRestaurantDeliveryLocationMutation,
  useUpdateBranchDeliveryLocationMutation,
  useUploadRestaurantLogoMutation,
  useGetPresignedUrlMutation,
  useGetRestaurantsQuery,
  useGetRestaurantQuery,
  useGetPricesQuery,
  useCreatePriceMutation,
  useGetInventoryListQuery,
  useGetInventoryQuery,
  useUpdateInventoryMutation,
  useCreateInventoryAdjustmentMutation,
  useGetWarehousesQuery,
  useCreateWarehouseMutation,
  useSetDefaultWarehouseMutation,
  useGetSupplierFulfillmentQuery,
  useUpdateSupplierFulfillmentMutation,
  useGetWarehouseRoutingRulesQuery,
  useSimulateWarehouseRoutingMutation,
  useGetOrderWarehouseAssignmentsQuery,
  useGetDashboardStatsQuery,
  useGetAuditLogsQuery,
  useGeneratePresignedUrlMutation,
  useAttachFileToProductMutation,
  useGetConversationsQuery,
  useStartSupportChatMutation,
  useGetSupportConversationsQuery,
  useGetAdminSupportConversationsQuery,
  useGetFeaturedPlacementPackagesQuery,
  useGetMyFeaturedPlacementsQuery,
  usePurchaseFeaturedPlacementMutation,
  useGetAdminFeaturedPlacementsQuery,
  useGetMessagesQuery,
  useCreateConversationMutation,
  useSendMessageMutation,
  useMarkConversationReadMutation,
  useMarkMessageReadMutation,
  usePinConversationMutation,
  useArchiveConversationMutation,
  useDeleteConversationMutation,
  useGetQuickListsQuery,
  useGetQuickListQuery,
  useCreateQuickListMutation,
  useUpdateQuickListMutation,
  useDeleteQuickListMutation,
  useAddItemToQuickListMutation,
  useRemoveItemFromQuickListMutation,
  useScheduleQuickListMutation,
  useUnscheduleQuickListMutation,
  useGetRestaurantInventoryQuery,
  useGetRestaurantInventoryHistoryQuery,
  useAddRestaurantInventoryMutation,
  useAdjustRestaurantInventoryMutation,
  useGetRestaurantWasteAnalyticsQuery,
  useGetReorderSuggestionsQuery,
  useGetExpiryLotsQuery,
  useGetExpirySummaryQuery,
  useCreateExpiryLotMutation,
  useUpdateExpiryLotMutation,
  useDeleteExpiryLotMutation,
  useGetReorderRemindersQuery,
  useGetReorderAssistanceQuery,
  useSuppressReorderSuggestionMutation,
  useGetOrderFulfillmentIssuesQuery,
  useReportOrderShortageMutation,
  useSuggestOrderSubstitutionIssueMutation,
  useOpenOrderFulfillmentChatMutation,
  useGetSupplierAtRiskOrdersQuery,
  useGetPendingOrdersForReceivingQuery,
  useGetReceivingHistoryQuery,
  useCreateReceivingReportMutation,
  useGetRestaurantInvoicesQuery,
  useGetRestaurantInvoiceQuery,
  useMarkInvoicePaidMutation,
  useRecordSupplierPaymentMutation,
  useGetInvoiceCreditsQuery,
  useGetInvoiceAnalyticsQuery,
  useGetOrderInvoicesQuery,
  useGetSupplierStatementQuery,
  useGetRestaurantExpensesQuery,
  useGetOverdueInvoicesQuery,
  useGetSupplierInvoicesQuery,
  useGetSupplierReceivablesQuery,
  useGetSupplierCommandCenterQuery,
  useGetSupplierReorderIntelligenceQuery,
  useGetSupplierReorderAssistanceQuery,
  useCreateReorderReminderDraftMutation,
  useGetSupplierDeliveryBoardQuery,
  usePreviewProductImportMutation,
  useExecuteProductImportMutation,
  useGetProductSubstitutesQuery,
  useCreateProductSubstituteMutation,
  useDeleteProductSubstituteMutation,
  useGetOrderSubstitutionsQuery,
  useProposeOrderSubstitutionMutation,
  useGetNotificationsQuery,
  useGetUnreadNotificationCountQuery,
  useGetNotificationPreferencesQuery,
  useUpdateNotificationPreferencesMutation,
  useGetBranchesQuery,
  useCreateBranchMutation,
  useUpdateBranchMutation,
  useDeleteBranchMutation,
  useSwitchBranchAccountMutation,
  useGetOrgQuery,
  useGetOrgBranchesQuery,
  useCreateOrgBranchMutation,
  useDeactivateOrgBranchMutation,
  useSwitchOrgBranchContextMutation,
  useGetBranchInviteRolesQuery,
  useGetBranchInvitationsQuery,
  useCreateBranchInvitationMutation,
  useRevokeBranchInvitationMutation,
  useRegenerateBranchInvitationMutation,
  useValidateBranchInviteQuery,
  useAcceptBranchInviteMutation,
  useValidateInviteQuery,
  useAcceptInviteMutation,
  useGetRestaurantOrgQuery,
  useGetRestaurantOrgBranchesQuery,
  useCreateRestaurantOrgBranchMutation,
  useSwitchRestaurantOrgBranchContextMutation,
  useDeactivateRestaurantOrgBranchMutation,
  useGetRestaurantMemberInviteRolesQuery,
  useGetRestaurantBranchInviteRolesQuery,
  useGetRestaurantMemberInvitationsQuery,
  useCreateRestaurantMemberInvitationMutation,
  useRevokeRestaurantMemberInvitationMutation,
  useRegenerateRestaurantMemberInvitationMutation,
  useGetRestaurantBranchInvitationsQuery,
  useCreateRestaurantBranchInvitationMutation,
  useRevokeRestaurantBranchInvitationMutation,
  useRegenerateRestaurantBranchInvitationMutation,
  useGetRestaurantTeamQuery,
  useAddRestaurantTeamMemberMutation,
  useDeleteRestaurantTeamMemberMutation,
  useGetTenantRolesQuery,
  useGetTenantRoleUsersQuery,
  useCreateTenantRoleMutation,
  useUpdateTenantRoleMutation,
  useDeleteTenantRoleMutation,
  useAssignTenantUserRoleMutation,
  useMarkNotificationReadMutation,
  useMarkAllNotificationsReadMutation,
  useGetPublicRestaurantQuery,
  useGetPublicSupplierQuery,
  useGetPublicSupplierProductsQuery,
  useGetPublicSupplierPricedProductsQuery,
  useGetQuoteRequestsQuery,
  useGetQuoteRequestDetailQuery,
  useGetQuoteRequestCompareQuery,
  useCreateQuoteRequestMutation,
  useConvertQuoteResponseToCartMutation,
  useGetSupplierQuoteInboxQuery,
  useGetSupplierQuoteRequestDetailQuery,
  useSubmitSupplierQuoteResponseMutation,
  useGetPublicReservationAvailabilityQuery,
  useLazyGetPublicReservationAvailabilityQuery,
  useCreatePublicReservationMutation,
  useJoinPublicWaitlistMutation,
  useGetPublicReservationDetailsQuery,
  useCancelPublicReservationMutation,
  useReschedulePublicReservationMutation,
  useRequestStaffPortalLinkMutation,
  useCreateStaffPortalSessionMutation,
  useGetStaffPortalDashboardQuery,
  useGetStaffPortalTimeEntriesQuery,
  useStaffPortalCheckInMutation,
  useStaffPortalCheckOutMutation,
  useSubmitStaffPortalPtoMutation,
  useSubmitStaffPortalSwapMutation,
  useGetStaffSelfDashboardQuery,
  useGetStaffSelfTimeEntriesQuery,
  useStaffSelfCheckInMutation,
  useStaffSelfCheckOutMutation,
  useSubmitStaffSelfPtoMutation,
  useSubmitStaffSelfSwapMutation,
  useAcknowledgeStaffPortalAnnouncementMutation,
  useAcknowledgeStaffSelfAnnouncementMutation,
  useGetStaffSelfAvailabilityQuery,
  useGetStaffPortalAvailabilityQuery,
  useSetStaffSelfAvailabilityMutation,
  useSetStaffPortalAvailabilityMutation,
  useGetCurrentSubscriptionQuery,
  useGetEntitlementsQuery,
  useGetRecommendationQuery,
  useGetSubscriptionPlansQuery,
  useRecordConversionEventMutation,
  useGetBillingStatusQuery,
  useGetBillingPaymentMethodsQuery,
  useAddBillingPaymentMethodMutation,
  useRemoveBillingPaymentMethodMutation,
  useBillingCheckoutMutation,
  useBillingPayNowMutation,
  useSetBillingAutoRenewMutation,
  useUnlockAdminSubscriptionMutation,
  useExtendAdminFreeTrialMutation,
  useGetSubscriptionUsageQuery,
  useCheckFeatureQuery,
  useGetRestaurantReportQuery,
  useGetSupplierReportQuery,
  useGetDisputesQuery,
  useGetIncomingDisputesQuery,
  useGetDisputeQuery,
  useCreateDisputeMutation,
  useCancelDisputeMutation,
  useReviewDisputeMutation,
  useResolveDisputeMutation,
  useRejectDisputeMutation,
  useGetCreditNotesQuery,
  useApplyCreditNoteMutation,
  useGetPromotionsQuery,
  useGetActivePromotionsQuery,
  useGetNewDealsBannerQuery,
  useDismissDealBannerMutation,
  useGetContractPricingQuery,
  useGetMyContractPricingQuery,
  useCreateContractPricingMutation,
  useUpdateContractPricingMutation,
  useDeactivateContractPricingMutation,
  useResolveContractPricesMutation,
  useCreatePromotionMutation,
  useUpdatePromotionMutation,
  useActivatePromotionMutation,
  usePausePromotionMutation,
  useDeletePromotionMutation,
  useGetPromotionAnalyticsQuery,
  useGetPromotionsAnalyticsSummaryQuery,
  useGetPromotionPricingQuery,
  useGetAdminPromotionPricingQuery,
  useGetDealDetailQuery,
  useGetEligibleDealProductsQuery,
  useRecordDealInteractionMutation,
  useUseDealCouponMutation,
  useMessageFromDealMutation,
  usePromoteDealMutation,
  useResumePromotionMutation,
  usePreviewDealQuery,
  useGetAdminDealsQuery,
  useGetAdminDealInsightsQuery,
  useGetAdminPendingDealsQuery,
  useApproveAdminDealMutation,
  useRejectAdminDealMutation,
  usePauseAdminDealMutation,
  useSubmitPromotionMutation,
  usePreviewCartDealMutation,
  useGetAdminLimitKeysQuery,
  useGetAdminLimitOverridesQuery,
  useCreateAdminPlanLimitOverrideMutation,
  useCreateAdminTenantLimitOverrideMutation,
  useGetAdminEffectiveLimitQuery,
  useUpdateAdminTenantLimitOverrideMutation,
  useUpdateAdminPlanLimitOverrideMutation,
  useUpdateAdminPromotionPricingMutation,
  useGetSupplierReviewsQuery,
  useGetSupplierRatingSummaryQuery,
  useGetMyReviewsQuery,
  useCreateSupplierReviewMutation,
  useUpdateReviewMutation,
  useDeleteReviewMutation,
  useGetTenantAuditLogFiltersQuery,
  useGetTenantAuditLogsQuery,
  useGetOrderAmendmentsQuery,
  useCreateOrderAmendmentMutation,
  useAcceptOrderAmendmentMutation,
  useRejectOrderAmendmentMutation,
  useCancelOrderAmendmentMutation,
  useGetVapidPublicKeyQuery,
  useSubscribePushMutation,
  useUnsubscribePushMutation,
  useAcceptWaitlistOfferMutation,
  useDeclineWaitlistOfferMutation,
  useGetAdminOverviewQuery,
  useGetAdminPlatformSettingsQuery,
  useUpdateAdminPlatformSettingsMutation,
  useGetAdminConversionStatsQuery,
  useGetAdminPlansQuery,
  useCreateAdminPlanMutation,
  useUpdateAdminPlanMutation,
  useGetAdminSubscriptionsQuery,
  useGetAdminSubscriptionAddonsQuery,
  useUpsertAdminSubscriptionAddonMutation,
  useUpdateAdminSubscriptionMutation,
  usePreviewSubscriptionPlanChangeMutation,
  useGetTenantUsageQuery,
  useGetAdminAuditLogsQuery,
  useGetAdminActivityQuery,
  useGetAdminHealthQuery,
  useGetAdminFinancialOverviewQuery,
  useGetAdminOperationalSummaryQuery,
  useGetAdminEmailDeliveryLogsQuery,
  useGetAdminFulfillmentIssuesQuery,
  useGetAdminActiveDeliveriesQuery,
  useGetAdminTenantOperationalSnapshotQuery,
  useGetAdminTenantEntitlementsQuery,
  useGetAdminSuppliersQuery,
  useGetAdminRestaurantsQuery,
  useGetAdminUsersQuery,
  useResetAdminUserPasswordMutation,
  useGetSupplierUsageQuery,
  useGetRestaurantUsageQuery,
  useGetImpersonationStatusQuery,
  useStartImpersonationMutation,
  useStopImpersonationMutation,
  useGetAdminFeatureFlagsQuery,
  useUpdateAdminFeatureFlagMutation,
  useGetTenantFeatureOverridesQuery,
  useSetTenantFeatureOverrideMutation,
  useClearTenantFeatureOverrideMutation,
} = api as any
