/** Realistic catalog + tenant definitions for business engineer demo. */

export const SEED_PASSWORD = process.env.SEED_ACCOUNTS_PASSWORD || 'Supplify1!'

export const BUSINESS_DEMO_PAIRS = [
  {
    supplier: {
      slug: 'be-demo-al-barsha-foods',
      name: 'Al Barsha Foods Trading',
      ownerEmail: 'supplier-al-barsha@supplify.com',
      vat: 'VAT-ALB-2024',
      phone: '+971501234501',
      address: {
        street: 'Warehouse 12, Al Barsha Industrial',
        city: 'Dubai',
        region: 'Dubai',
        country: 'UAE',
      },
      catalogName: 'Al Barsha Produce & Proteins',
      skuPrefix: 'ALB',
    },
    restaurant: {
      slug: 'be-demo-marina-trattoria',
      name: 'Marina Trattoria',
      ownerEmail: 'restaurant-marina@supplify.com',
      tradeLicense: 'TL-MARINA-8821',
      phone: '+971507654501',
      address: {
        street: 'Marina Walk, Tower 3',
        city: 'Dubai',
        region: 'Dubai',
        country: 'UAE',
      },
      branchName: 'Dubai Marina',
      branchCode: 'DXB-MARINA',
    },
  },
  {
    supplier: {
      slug: 'be-demo-gulf-chef-supply',
      name: 'Gulf Chef Provisions',
      ownerEmail: 'supplier-gulf-chef@supplify.com',
      vat: 'VAT-GCP-2024',
      phone: '+971501234502',
      address: {
        street: 'Jebel Ali Free Zone, Unit 8',
        city: 'Dubai',
        region: 'Dubai',
        country: 'UAE',
      },
      catalogName: 'Gulf Chef Wholesale',
      skuPrefix: 'GCP',
    },
    restaurant: {
      slug: 'be-demo-sahel-kitchen',
      name: 'Sahel Kitchen & Grill',
      ownerEmail: 'restaurant-sahel@supplify.com',
      tradeLicense: 'TL-SAHEL-4410',
      phone: '+971507654502',
      address: {
        street: 'Business Bay, Bay Square 2',
        city: 'Dubai',
        region: 'Dubai',
        country: 'UAE',
      },
      branchName: 'Business Bay',
      branchCode: 'DXB-BAY',
    },
  },
]

/** @param {string} sku */
export function productImageUrl(sku) {
  return `https://picsum.photos/seed/${encodeURIComponent(sku)}/480/360`
}

export const AL_BARSHA_PRODUCTS = [
  {
    sku: 'ALB-001',
    name: 'Vine-Ripened Tomatoes',
    category: 'Vegetables',
    unit: 'kg',
    price: 2.85,
    description: 'Local greenhouse tomatoes, ideal for sauces and salads.',
  },
  {
    sku: 'ALB-002',
    name: 'Baby Spinach',
    category: 'Vegetables',
    unit: 'pack',
    price: 3.2,
    description: 'Triple-washed baby spinach, 500g retail packs.',
  },
  {
    sku: 'ALB-003',
    name: 'Hass Avocados',
    category: 'Vegetables',
    unit: 'kg',
    price: 6.5,
    description: 'Ripe Hass avocados sorted for foodservice.',
  },
  {
    sku: 'ALB-004',
    name: 'Fresh Basil Bunch',
    category: 'Herbs',
    unit: 'bunch',
    price: 1.9,
    description: 'Fragrant basil harvested same-day.',
  },
  {
    sku: 'ALB-005',
    name: 'Buffalo Mozzarella',
    category: 'Dairy',
    unit: 'kg',
    price: 14.5,
    description: 'Imported buffalo mozzarella, 125g balls per case.',
  },
  {
    sku: 'ALB-006',
    name: 'Parmigiano Reggiano Wedge',
    category: 'Dairy',
    unit: 'kg',
    price: 22.0,
    description: '24-month aged Parmigiano, wheel-cut.',
  },
  {
    sku: 'ALB-007',
    name: 'Chicken Breast Fillet',
    category: 'Poultry',
    unit: 'kg',
    price: 9.8,
    description: 'Halal skinless breast, 180–220g portions.',
  },
  {
    sku: 'ALB-008',
    name: 'Atlantic Salmon Fillet',
    category: 'Seafood',
    unit: 'kg',
    price: 28.5,
    description: 'Skin-on salmon fillets, sushi-grade chilled.',
  },
  {
    sku: 'ALB-009',
    name: 'Arborio Rice',
    category: 'Dry Goods',
    unit: 'kg',
    price: 4.1,
    description: 'Italian risotto rice, 5kg chef bags.',
  },
  {
    sku: 'ALB-010',
    name: 'Extra Virgin Olive Oil',
    category: 'Oils',
    unit: 'bottle',
    price: 11.5,
    description: 'Cold-pressed EVOO, 1L tin for pasta stations.',
  },
  {
    sku: 'ALB-011',
    name: 'San Marzano Tomatoes (tin)',
    category: 'Dry Goods',
    unit: 'tin',
    price: 3.75,
    description: 'DOP peeled tomatoes, 2.5kg catering tins.',
  },
  {
    sku: 'ALB-012',
    name: 'Fresh Egg Pasta Tagliatelle',
    category: 'Pasta',
    unit: 'kg',
    price: 7.2,
    description: 'Daily-fresh tagliatelle, 2kg trays.',
  },
  {
    sku: 'ALB-013',
    name: 'Burrata Cheese',
    category: 'Dairy',
    unit: 'piece',
    price: 4.8,
    description: '200g burrata, packed in whey.',
  },
  {
    sku: 'ALB-014',
    name: 'Wild Rocket',
    category: 'Vegetables',
    unit: 'pack',
    price: 2.6,
    description: 'Peppery rocket, 250g clamshell.',
  },
  {
    sku: 'ALB-015',
    name: 'Lemons (seedless)',
    category: 'Fruit',
    unit: 'kg',
    price: 2.2,
    description: 'South African seedless lemons, high juice yield.',
  },
  {
    sku: 'ALB-016',
    name: 'Garlic Peeled',
    category: 'Vegetables',
    unit: 'kg',
    price: 5.4,
    description: 'Ready-peeled garlic cloves, foodservice tub.',
  },
  {
    sku: 'ALB-017',
    name: 'Heavy Cream',
    category: 'Dairy',
    unit: 'liter',
    price: 6.9,
    description: '35% fat cream, UHT 1L packs.',
  },
  {
    sku: 'ALB-018',
    name: 'Sea Salt Flakes',
    category: 'Dry Goods',
    unit: 'kg',
    price: 8.0,
    description: 'Maldon-style finishing salt, 1kg tub.',
  },
  {
    sku: 'ALB-019',
    name: 'Sourdough Loaf',
    category: 'Bakery',
    unit: 'loaf',
    price: 3.5,
    description: 'Artisan sourdough, baked 04:00 daily.',
  },
  {
    sku: 'ALB-020',
    name: 'Sparkling Mineral Water',
    category: 'Beverages',
    unit: 'case',
    price: 18.0,
    description: '330ml glass bottles, 24-pack.',
  },
]

export const GULF_CHEF_PRODUCTS = [
  {
    sku: 'GCP-001',
    name: 'Australian Lamb Chops',
    category: 'Meat',
    unit: 'kg',
    price: 19.5,
    description: 'Frenched lamb racks, halal certified.',
  },
  {
    sku: 'GCP-002',
    name: 'Wagyu Burger Patties',
    category: 'Meat',
    unit: 'kg',
    price: 32.0,
    description: '180g patties, 80/20 blend, frozen IQF.',
  },
  {
    sku: 'GCP-003',
    name: 'Jumbo Prawns U15',
    category: 'Seafood',
    unit: 'kg',
    price: 24.0,
    description: 'Head-on prawns, deveined, 1kg net.',
  },
  {
    sku: 'GCP-004',
    name: 'Halloumi Cheese Block',
    category: 'Dairy',
    unit: 'kg',
    price: 12.5,
    description: 'Cyprus halloumi, grill-ready 1kg blocks.',
  },
  {
    sku: 'GCP-005',
    name: 'Flatbread (khubz)',
    category: 'Bakery',
    unit: 'pack',
    price: 2.8,
    description: 'Fresh khameer bread, 12 pieces per bag.',
  },
  {
    sku: 'GCP-006',
    name: 'Tahini Paste',
    category: 'Dry Goods',
    unit: 'kg',
    price: 7.5,
    description: 'Stone-ground sesame tahini, 5kg pail.',
  },
  {
    sku: 'GCP-007',
    name: 'Sumac Spice',
    category: 'Spices',
    unit: 'kg',
    price: 9.0,
    description: 'Ground sumac for fattoush and grills.',
  },
  {
    sku: 'GCP-008',
    name: 'Medjool Dates',
    category: 'Fruit',
    unit: 'kg',
    price: 11.0,
    description: 'Premium Medjool, dessert and garnish grade.',
  },
  {
    sku: 'GCP-009',
    name: 'Persian Cucumbers',
    category: 'Vegetables',
    unit: 'kg',
    price: 2.4,
    description: 'Snack cucumbers, 15cm uniform size.',
  },
  {
    sku: 'GCP-010',
    name: 'Mixed Grill Vegetables',
    category: 'Vegetables',
    unit: 'kg',
    price: 3.9,
    description: 'Courgette, pepper, onion chef mix.',
  },
  {
    sku: 'GCP-011',
    name: 'Beef Tenderloin',
    category: 'Meat',
    unit: 'kg',
    price: 38.0,
    description: 'Center-cut tenderloin, trimmed chain off.',
  },
  {
    sku: 'GCP-012',
    name: 'Chicken Thigh Boneless',
    category: 'Poultry',
    unit: 'kg',
    price: 7.2,
    description: 'Marinated-ready thighs, skinless.',
  },
  {
    sku: 'GCP-013',
    name: 'Hummus Base (chickpeas)',
    category: 'Dry Goods',
    unit: 'kg',
    price: 2.1,
    description: 'Soaked-ready chickpeas, 5kg vacuum pack.',
  },
  {
    sku: 'GCP-014',
    name: 'Pomegranate Molasses',
    category: 'Sauces',
    unit: 'bottle',
    price: 5.5,
    description: 'Lebanese molasses, 500ml squeeze bottle.',
  },
  {
    sku: 'GCP-015',
    name: 'Lamb Kofta Mince',
    category: 'Meat',
    unit: 'kg',
    price: 14.0,
    description: 'Seasoned lamb mince for kofta skewers.',
  },
  {
    sku: 'GCP-016',
    name: 'Fattoush Dressing',
    category: 'Sauces',
    unit: 'liter',
    price: 8.5,
    description: 'Ready-to-pour fattoush dressing, 2L jug.',
  },
  {
    sku: 'GCP-017',
    name: 'Charcoal (restaurant grade)',
    category: 'Supplies',
    unit: 'bag',
    price: 15.0,
    description: 'Hardwood lump charcoal, 10kg bags.',
  },
  {
    sku: 'GCP-018',
    name: 'Labneh',
    category: 'Dairy',
    unit: 'kg',
    price: 6.0,
    description: 'Strained yogurt spread, 2kg tub.',
  },
  {
    sku: 'GCP-019',
    name: 'Mint Leaves',
    category: 'Herbs',
    unit: 'bunch',
    price: 1.5,
    description: 'Fresh spearmint for tea and salads.',
  },
  {
    sku: 'GCP-020',
    name: 'Rose Water',
    category: 'Beverages',
    unit: 'bottle',
    price: 4.2,
    description: 'Food-grade rose water, 500ml.',
  },
]

export function productsForSupplier(def) {
  if (def.skuPrefix === 'ALB') return AL_BARSHA_PRODUCTS
  if (def.skuPrefix === 'GCP') return GULF_CHEF_PRODUCTS
  return []
}

export const DEAL_TEMPLATES = [
  {
    name: 'Chef’s Choice 12% Off',
    description: 'Twelve percent off qualifying produce and proteins this week.',
    type: 'percentage_discount',
    discount_value: 12,
    min_order_amount: 150,
    max_discount_cap: 120,
    is_featured: true,
    imageLabel: 'Chef+Choice+12',
  },
  {
    name: 'Free delivery on large orders',
    description: 'Waived delivery fee on orders above AED 500 equivalent.',
    type: 'free_shipping',
    discount_value: 25,
    min_order_amount: 500,
    max_discount_cap: 25,
    is_featured: false,
    imageLabel: 'Free+Delivery',
  },
  {
    name: 'Case deal: buy 10 get 2',
    description: 'Stock up on staples — buy 10 cases, get 2 free on selected SKUs.',
    type: 'buy_x_get_y',
    buy_quantity: 10,
    get_quantity: 2,
    min_order_amount: 300,
    is_featured: true,
    imageLabel: 'Bulk+Deal',
  },
]
