-- Migration: 0052_conversion_event_types.sql
-- Add funnel event types: CLICK_UPGRADE, CLOSE_UPGRADE_MODAL, DOWNGRADE_ATTEMPT_BLOCKED, RECOMMENDATION_SHOWN, RECOMMENDATION_CLICKED

ALTER TABLE conversion_event DROP CONSTRAINT IF EXISTS conversion_event_event_type_check;
ALTER TABLE conversion_event ADD CONSTRAINT conversion_event_event_type_check CHECK (event_type IN (
  'VIEW_PLANS',
  'BLOCKED_FEATURE',
  'BLOCKED_LIMIT',
  'OPEN_UPGRADE',
  'UPGRADE_SUCCESS',
  'CLICK_UPGRADE',
  'CLOSE_UPGRADE_MODAL',
  'DOWNGRADE_ATTEMPT_BLOCKED',
  'RECOMMENDATION_SHOWN',
  'RECOMMENDATION_CLICKED'
));
