export const PERMISSION_LABELS = {
  ORDERS_VIEW: 'View orders',
  ORDERS_CREATE: 'Place orders',
  ORDERS_EDIT: 'Edit orders',
  ORDERS_MANAGE: 'Manage & approve orders',
  INVOICES_VIEW: 'View invoices',
  INVOICES_CREATE: 'Create invoices',
  INVOICES_EDIT: 'Edit invoices',
  INVOICES_MANAGE: 'Manage all invoices',
  INVENTORY_VIEW: 'View inventory',
  INVENTORY_EDIT: 'Edit stock levels',
  INVENTORY_MANAGE: 'Full inventory control',
  RESERVATIONS_VIEW: 'View reservations',
  RESERVATIONS_CREATE: 'Create bookings',
  RESERVATIONS_EDIT: 'Edit bookings',
  RESERVATIONS_MANAGE: 'Manage all reservations',
  STAFF_VIEW: 'View staff',
  STAFF_INVITE: 'Invite team members',
  STAFF_EDIT: 'Edit staff records',
  STAFF_MANAGE: 'Full staff management',
  SETTINGS_VIEW: 'View settings',
  SETTINGS_EDIT: 'Edit settings',
  SETTINGS_MANAGE: 'Full settings control',
  CHAT_VIEW: 'View messages',
  CHAT_SEND: 'Send messages',
  CHAT_MANAGE: 'Manage all conversations',
  SUBSCRIPTIONS_VIEW: 'View subscription & plan',
  SUBSCRIPTIONS_MANAGE: 'Change plan & billing',
  CATALOG_VIEW: 'View product catalog',
  CATALOG_EDIT: 'Edit products & prices',
  CATALOG_MANAGE: 'Full catalog management',
  WAREHOUSES_VIEW: 'View warehouses',
  WAREHOUSES_EDIT: 'Edit warehouse details',
  WAREHOUSES_MANAGE: 'Full warehouse management',
  RECEIVING_VIEW: 'View receiving reports',
  RECEIVING_MANAGE: 'Manage receiving',
  PAYMENTS_VIEW: 'View payments',
  PAYMENTS_MANAGE: 'Process payments',
  FULFILLMENT_VIEW: 'View fulfillment board',
  FULFILLMENT_MANAGE: 'Manage fulfillment',
  PROMOTIONS_VIEW: 'View promotions',
  PROMOTIONS_MANAGE: 'Manage promotions',
  DRIVER_DELIVERIES_VIEW: 'View assigned deliveries',
  DRIVER_DELIVERIES_MANAGE: 'Update delivery status & proof',
  ADMIN_ACCESS: 'Platform admin access',
}

export const PERMISSION_DOMAINS = {
  Orders: ['ORDERS_VIEW', 'ORDERS_CREATE', 'ORDERS_EDIT', 'ORDERS_MANAGE'],
  Invoices: ['INVOICES_VIEW', 'INVOICES_CREATE', 'INVOICES_EDIT', 'INVOICES_MANAGE'],
  Inventory: ['INVENTORY_VIEW', 'INVENTORY_EDIT', 'INVENTORY_MANAGE'],
  Reservations: [
    'RESERVATIONS_VIEW',
    'RESERVATIONS_CREATE',
    'RESERVATIONS_EDIT',
    'RESERVATIONS_MANAGE',
  ],
  Staff: ['STAFF_VIEW', 'STAFF_INVITE', 'STAFF_EDIT', 'STAFF_MANAGE'],
  Settings: ['SETTINGS_VIEW', 'SETTINGS_EDIT', 'SETTINGS_MANAGE'],
  Chat: ['CHAT_VIEW', 'CHAT_SEND', 'CHAT_MANAGE'],
  Subscriptions: ['SUBSCRIPTIONS_VIEW', 'SUBSCRIPTIONS_MANAGE'],
  Catalog: ['CATALOG_VIEW', 'CATALOG_EDIT', 'CATALOG_MANAGE'],
  Warehouses: ['WAREHOUSES_VIEW', 'WAREHOUSES_EDIT', 'WAREHOUSES_MANAGE'],
  Receiving: ['RECEIVING_VIEW', 'RECEIVING_MANAGE'],
  Payments: ['PAYMENTS_VIEW', 'PAYMENTS_MANAGE'],
  Fulfillment: ['FULFILLMENT_VIEW', 'FULFILLMENT_MANAGE'],
  Promotions: ['PROMOTIONS_VIEW', 'PROMOTIONS_MANAGE'],
  'Driver deliveries': ['DRIVER_DELIVERIES_VIEW', 'DRIVER_DELIVERIES_MANAGE'],
}

export const RESTAURANT_PERMISSION_DOMAINS = {
  Orders: PERMISSION_DOMAINS.Orders,
  Invoices: PERMISSION_DOMAINS.Invoices,
  Inventory: PERMISSION_DOMAINS.Inventory,
  Reservations: PERMISSION_DOMAINS.Reservations,
  Staff: PERMISSION_DOMAINS.Staff,
  Settings: PERMISSION_DOMAINS.Settings,
  Chat: PERMISSION_DOMAINS.Chat,
  Subscriptions: PERMISSION_DOMAINS.Subscriptions,
  Receiving: PERMISSION_DOMAINS.Receiving,
  Payments: PERMISSION_DOMAINS.Payments,
}

export const SUPPLIER_PERMISSION_DOMAINS = {
  Orders: PERMISSION_DOMAINS.Orders,
  Invoices: PERMISSION_DOMAINS.Invoices,
  Inventory: PERMISSION_DOMAINS.Inventory,
  Catalog: PERMISSION_DOMAINS.Catalog,
  Warehouses: PERMISSION_DOMAINS.Warehouses,
  Staff: PERMISSION_DOMAINS.Staff,
  Settings: PERMISSION_DOMAINS.Settings,
  Chat: PERMISSION_DOMAINS.Chat,
  Subscriptions: PERMISSION_DOMAINS.Subscriptions,
  Receiving: PERMISSION_DOMAINS.Receiving,
  Payments: PERMISSION_DOMAINS.Payments,
  Fulfillment: PERMISSION_DOMAINS.Fulfillment,
  Promotions: PERMISSION_DOMAINS.Promotions,
  'Driver deliveries': PERMISSION_DOMAINS['Driver deliveries'],
}

export function labelForPermission(key) {
  return PERMISSION_LABELS[key] || key
}
